services:
  users-db:
    image: postgres:16
    container_name: users-db
    environment:
      POSTGRES_USER: raghav
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    volumes:
      - users-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U raghav -d default" ]
      interval: 5s
      timeout: 5s
      retries: 10

  email-db:
    image: mongo:7
    container_name: email-db
    command: [ "mongod", "--quiet", "--logpath", "/dev/null" ] # disable useless logs
    environment:
      MONGO_INITDB_ROOT_USERNAME: raghav
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: default
    volumes:
      - email-db:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: public.ecr.aws/bitnami/kafka:3.9.0
    container_name: kafka
    command: [ "bash", "-c", "exec >/dev/null 2>&1 && /opt/bitnami/scripts/kafka/run.sh" ]
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      ALLOW_PLAINTEXT_LISTENER: yes
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-broker-api-versions.sh --bootstrap-server kafka:9092 || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./api-gateway
          target: /app
          ignore:
            - target/
            - "**/mvnw"
            - "**/mvnw.cmd"
            - "**/.mvn/"
        - action: rebuild
          path: ./api-gateway/pom.xml

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    container_name: auth-service
    depends_on:
      users-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./auth-service
          target: /app
          ignore:
            - target/
            - "**/mvnw"
            - "**/mvnw.cmd"
            - "**/.mvn/"
        - action: rebuild
          path: ./auth-service/pom.xml

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev
    container_name: user-service
    depends_on:
      users-db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./user-service
          target: /app
          ignore:
            - target/
            - "**/mvnw"
            - "**/mvnw.cmd"
            - "**/.mvn/"
        - action: rebuild
          path: ./user-service/pom.xml

  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile.dev
    container_name: email-service
    depends_on:
      email-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./email-service
          target: /app
          ignore:
            - target/
            - "**/mvnw"
            - "**/mvnw.cmd"
            - "**/.mvn/"
        - action: rebuild
          path: ./email-service/pom.xml

volumes:
  users-db:
  email-db: