services:
  users-db:
    image: postgres:16
    container_name: users-db
    environment:
      POSTGRES_USER: raghav
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    volumes:
      - users-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U raghav -d default" ]
      interval: 5s
      timeout: 5s
      retries: 10

  email-db:
    image: mongo:7
    container_name: email-db
    command: [ "mongod", "--quiet", "--logpath", "/dev/null" ] # disable useless logs
    environment:
      MONGO_INITDB_ROOT_USERNAME: raghav
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: default
    volumes:
      - email-db:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 10

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./api-gateway
          target: /app
          ignore:
            - target/
            - "**/mvnw"
            - "**/mvnw.cmd"
            - "**/.mvn/"
        - action: rebuild
          path: ./api-gateway/pom.xml

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    container_name: auth-service
    depends_on:
      users-db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./auth-service
          target: /app
          ignore:
            - target/
            - "**/mvnw"
            - "**/mvnw.cmd"
            - "**/.mvn/"
        - action: rebuild
          path: ./auth-service/pom.xml

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev
    container_name: user-service
    depends_on:
      users-db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./user-service
          target: /app
          ignore:
            - target/
            - "**/mvnw"
            - "**/mvnw.cmd"
            - "**/.mvn/"
        - action: rebuild
          path: ./user-service/pom.xml

  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile.dev
    container_name: email-service
    depends_on:
      email-db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./email-service
          target: /app
          ignore:
            - target/
            - "**/mvnw"
            - "**/mvnw.cmd"
            - "**/.mvn/"
        - action: rebuild
          path: ./email-service/pom.xml

volumes:
  users-db:
  email-db: