server:
  port: 8082

grpc:
  server:
    port: 9092

auth:
  service:
    host: auth-service
    grpc:
      port: 9091

spring:
  datasource:
    url: jdbc:postgresql://users-db:5432/default
    username: raghav
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false