server:
  port: 8083

logging:
  level:
    org.mongodb: OFF
    com.mongodb: OFF
    org.apache.kafka: OFF
    org.springframework.kafka: OFF

spring:
  data:
    mongodb:
      uri: mongodb://raghav:password@email-db:27017/default?authSource=admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: raghavbhagat32@gmail.com
    password: jgdl ubtp yyuf eeqj
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: spring-kafka-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.rbhagat32.emailservice.entity.EmailEntity